table Sentiment
	lineageTag: bc685a49-faee-4481-a632-133704f13102

	column Sentiment
		dataType: string
		lineageTag: 7eb868e0-5e34-4fe6-891c-14789eb8f797
		summarizeBy: none
		sourceColumn: Sentiment
		sortByColumn: Sort_Order

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Sort_Order
		dataType: int64
		formatString: 0
		lineageTag: f0dc67d4-c61d-4f4c-b54e-11cf91b3e9bd
		summarizeBy: none
		sourceColumn: Sort_Order

		annotation SummarizationSetBy = Automatic

	partition Sentiment = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WCsgvzizJLEtV0lEyVIrViVbySy0tKUrMAfKNoPz0RKgCY6XYWAA=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Sentiment = _t, Sort_Order = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Sentiment", type text}, {"Sort_Order", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

